# Generated by Django 3.2.8 on 2021-11-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('N', 'Not Started'), ('I', 'In Progress'), ('C', 'Complete')], max_length=1)),
                ('total_time', models.IntegerField()),
            ],
        ),
    ]
