# Generated by Django 3.2.8 on 2021-12-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20211201_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
