# Generated by Django 3.2.8 on 2021-12-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_timeentry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='task_title',
            field=models.CharField(default='placeholder', max_length=200),
        ),
    ]
