# Generated by Django 3.2.8 on 2021-11-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.CharField(max_length=10),
        ),
    ]
