# Generated by Django 3.2.8 on 2021-12-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_timeentry_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='time_elapsed',
            field=models.CharField(default='placeholder', max_length=200),
        ),
    ]
